const state = {
    page: 'auth',
    auth: null,
    categories: [],
    menuItems: [],
    lessons: [],
    testList: [],
    users: [],
    roles: [],
    history: [],
    adminResults: [],
    menuSearch: '',
    menuCatId: null,
    activeLessonId: null,
    activeTest: null,
    testAnswers: {},
    currentQuestion: 0,
    testStartedAt: null,
    timerSecs: 0,
    timerInterval: null,
    quizzesPassed: 0,
    lastResult: null,
    loading: false,
    error: null,
    theme: localStorage.getItem('sc_theme') || 'light'
  };